### ISSUE TITLE
Allow less plug connections

### ISSUE THREAD

**Issue by chinesedfan** [GabrielIDSM/WebEncryptor#1]
If the machine supports 10 plug connections, we want to use only 8 or 9.

Or the API can allow same plug letters in pair.

See https://github.com/GabrielIDSM/Web-Encryptor-API/blob/8aeb1081ad835b7da4d4f4f07e29621259da305d/src/main/java/br/com/GabrielIDSM/EncryptorAPI/LogicalTier/EnigmaM4/DataValidationToEnigmaM4WithPlugboardAndThreeRotors.java#L25.

**Comment by GabrielIDSM** [comment]
Thanks for the sugestion!

I'll do something about it.

**Comment by GabrielIDSM** [comment]
Hi

Now, you can use "encryptorapi-gabrielidsm.herokuapp.com/**free**/" instead "encryptorapi-gabrielidsm.herokuapp.com/**message**/"

In this endpoint there is no data validation.

Good Luck!
